################################################################################
############################ Variables to change ###############################
##### Sources directory
SRC_DIR            =

##### Main file, without .tex extension.
NAME               =

##### Included TeX files in the main file $(NAME).tex.
INCLUDED_TEX_FILES =
##### Output directory (without / at the end).
# If not modified, it is the directory which holds the MakeFile.
OUTPUT_DIR         =

##### Executable/output to use: PDFLATEX, DVILUATEX
CC                 = $(PDFLATEX)
CC_BIB             = $(BIBTEX)
USE_BIB            = false
################################################################################
